### ISSUE TITLE
Restrict access to xmlrpc.php in Pyrocms

### ISSUE THREAD

**Issue by abdulrashid9** [pyrocms/pyrocms-docs#178]
I recently noted a huge amount of traffic hitting to the xmlrpc.php

I blocked the IP address which is a temparary solution. How I block access to xmlrpc.php file in Pyrocms.

**Comment by RyanThompson** [comment]
Hi there - I am a little lost in what you're saying? Like you're under an XMLRPC attack? Or Pyro is making calls to something of yours?

**Comment by abdulrashid9** [comment]
Yes i am under XMLRPC attack and i want block access to xmlrpc.php.

**Comment by RyanThompson** [comment]
You will need to do a little research I think - this has less to do with CodeIgniter / PyroCMS and more to do with PHP in general and security. Looks like there are a lot of resource out there to help out with something like this.

**Comment by abdulrashid9** [comment]
I know how this can achieve in wordpress, But very hard to find in CodeIgniter / PyroCMS.

**Comment by RyanThompson** [comment]
The same approach can not be used?

**Comment by abdulrashid9** [comment]
Yes i know thanks for your time.

**Comment by RyanThompson** [comment]
Sure, sorry I could not be of more help!


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581
